"""add_created_at_updated_at_to_enterprise_members

Revision ID: 1fe9cceec15a
Revises: 0003
Create Date: 2026-02-13 15:27:46.615897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fe9cceec15a'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'asset_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_comment='资产元数据（JSON 格式）',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.add_column('attachments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('attachments', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('attachments_ipfs_cid_key'), 'attachments', type_='unique')
    op.drop_index(op.f('ix_attachments_ipfs_cid'), table_name='attachments')
    op.create_index(op.f('ix_attachments_ipfs_cid'), 'attachments', ['ipfs_cid'], unique=True)
    op.add_column('enterprise_members', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('enterprise_members', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('enterprises_wallet_address_key'), 'enterprises', type_='unique')
    op.drop_index(op.f('ix_enterprises_wallet_address'), table_name='enterprises')
    op.create_index(op.f('ix_enterprises_wallet_address'), 'enterprises', ['wallet_address'], unique=True)
    op.add_column('refresh_tokens', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('refresh_tokens', 'token_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'device_info',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_constraint(op.f('refresh_tokens_token_hash_key'), 'refresh_tokens', type_='unique')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_wallet_address_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_wallet_address_key'), 'users', ['wallet_address'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_unique_constraint(op.f('refresh_tokens_token_hash_key'), 'refresh_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.alter_column('refresh_tokens', 'device_info',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('refresh_tokens', 'token_hash',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('refresh_tokens', 'updated_at')
    op.drop_index(op.f('ix_enterprises_wallet_address'), table_name='enterprises')
    op.create_index(op.f('ix_enterprises_wallet_address'), 'enterprises', ['wallet_address'], unique=False)
    op.create_unique_constraint(op.f('enterprises_wallet_address_key'), 'enterprises', ['wallet_address'], postgresql_nulls_not_distinct=False)
    op.drop_column('enterprise_members', 'updated_at')
    op.drop_column('enterprise_members', 'created_at')
    op.drop_index(op.f('ix_attachments_ipfs_cid'), table_name='attachments')
    op.create_index(op.f('ix_attachments_ipfs_cid'), 'attachments', ['ipfs_cid'], unique=False)
    op.create_unique_constraint(op.f('attachments_ipfs_cid_key'), 'attachments', ['ipfs_cid'], postgresql_nulls_not_distinct=False)
    op.drop_column('attachments', 'updated_at')
    op.drop_column('attachments', 'created_at')
    op.alter_column('assets', 'asset_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='资产元数据（JSON 格式）',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###
