"""add_address_field_to_enterprises

Revision ID: a6e6734984b9
Revises: e1c24756548b
Create Date: 2026-02-15 14:02:41.462354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6e6734984b9'
down_revision: Union[str, None] = 'e1c24756548b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprises', sa.Column('address', sa.String(length=500), nullable=True, comment='企业地址'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enterprises', 'address')
    # ### end Alembic commands ###
