"""add_password_reset_and_email_verification_tokens

Revision ID: a44b7efcd33a
Revises: a6e6734984b9
Create Date: 2026-02-16 12:06:19.025068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a44b7efcd33a'
down_revision: Union[str, None] = 'a6e6734984b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='SHA-256哈希后的令牌值'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='需要验证邮箱的用户ID'),
    sa.Column('is_used', sa.Boolean(), nullable=False, comment='标记令牌是否已被使用'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='令牌创建时间'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='令牌过期时间（默认24小时）'),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, comment='令牌使用时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_verification_tokens_expires_at', 'email_verification_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_email_verification_tokens_token_hash'), 'email_verification_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_index('ix_email_verification_tokens_user_is_used', 'email_verification_tokens', ['user_id', 'is_used'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='SHA-256哈希后的令牌值'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='请求密码重置的用户ID'),
    sa.Column('is_used', sa.Boolean(), nullable=False, comment='标记令牌是否已被使用'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='令牌创建时间'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='令牌过期时间（默认30分钟）'),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, comment='令牌使用时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_password_reset_tokens_expires_at', 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index('ix_password_reset_tokens_user_is_used', 'password_reset_tokens', ['user_id', 'is_used'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_password_reset_tokens_user_is_used', table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index('ix_password_reset_tokens_expires_at', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index('ix_email_verification_tokens_user_is_used', table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token_hash'), table_name='email_verification_tokens')
    op.drop_index('ix_email_verification_tokens_expires_at', table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    # ### end Alembic commands ###
