"""add_approval_models

Revision ID: e1c24756548b
Revises: 1fe9cceec15a
Create Date: 2026-02-14 13:37:16.885100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1c24756548b'
down_revision: Union[str, None] = '1fe9cceec15a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.UUID(), nullable=False, comment='审批唯一标识符'),
    sa.Column('type', sa.Enum('ENTERPRISE_CREATE', 'ENTERPRISE_UPDATE', 'MEMBER_JOIN', name='approvaltype'), nullable=False, comment='审批类型'),
    sa.Column('target_id', sa.UUID(), nullable=False, comment='目标对象ID（企业ID或成员关系ID）'),
    sa.Column('target_type', sa.String(length=32), nullable=False, comment='目标类型: enterprise, member'),
    sa.Column('applicant_id', sa.UUID(), nullable=False, comment='申请人用户ID'),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'RETURNED', name='approvalstatus'), nullable=False, comment='审批状态'),
    sa.Column('current_step', sa.Integer(), nullable=False, comment='当前步骤序号'),
    sa.Column('total_steps', sa.Integer(), nullable=False, comment='总步骤数'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='申请备注/理由'),
    sa.Column('attachments', sa.JSON(), nullable=True, comment='附件列表（JSON格式）'),
    sa.Column('changes', sa.JSON(), nullable=True, comment='变更内容（JSON格式，存储变更前后的值）'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='审批完成时间'),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_applicant_id'), 'approvals', ['applicant_id'], unique=False)
    op.create_index('ix_approvals_created_at', 'approvals', ['created_at'], unique=False)
    op.create_index(op.f('ix_approvals_status'), 'approvals', ['status'], unique=False)
    op.create_index('ix_approvals_status_type', 'approvals', ['status', 'type'], unique=False)
    op.create_index('ix_approvals_target_id', 'approvals', ['target_id'], unique=False)
    op.create_index('ix_approvals_type', 'approvals', ['type'], unique=False)
    op.create_table('approval_notifications',
    sa.Column('id', sa.UUID(), nullable=False, comment='通知唯一标识符'),
    sa.Column('type', sa.String(length=32), nullable=False, comment='通知类型: approval_request, approval_result, approval_reminder'),
    sa.Column('recipient_id', sa.UUID(), nullable=False, comment='接收人用户ID'),
    sa.Column('approval_id', sa.UUID(), nullable=True, comment='关联审批ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='通知标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='通知内容'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='是否已读'),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True, comment='阅读时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_notifications_approval_id'), 'approval_notifications', ['approval_id'], unique=False)
    op.create_index('ix_approval_notifications_created_at', 'approval_notifications', ['created_at'], unique=False)
    op.create_index('ix_approval_notifications_is_read', 'approval_notifications', ['is_read'], unique=False)
    op.create_index('ix_approval_notifications_recipient_id', 'approval_notifications', ['recipient_id'], unique=False)
    op.create_index('ix_approval_notifications_recipient_read', 'approval_notifications', ['recipient_id', 'is_read'], unique=False)
    op.create_table('approval_processes',
    sa.Column('id', sa.UUID(), nullable=False, comment='流程记录唯一标识符'),
    sa.Column('approval_id', sa.UUID(), nullable=False, comment='关联审批ID'),
    sa.Column('step', sa.Integer(), nullable=False, comment='步骤序号'),
    sa.Column('action', sa.Enum('SUBMIT', 'APPROVE', 'REJECT', 'RETURN', 'TRANSFER', name='approvalaction'), nullable=False, comment='操作类型'),
    sa.Column('operator_id', sa.UUID(), nullable=False, comment='操作人用户ID'),
    sa.Column('operator_role', sa.String(length=32), nullable=True, comment='操作人角色'),
    sa.Column('comment', sa.Text(), nullable=True, comment='审批意见'),
    sa.Column('attachments', sa.JSON(), nullable=True, comment='附件列表（JSON格式）'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='操作时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_processes_approval_id'), 'approval_processes', ['approval_id'], unique=False)
    op.create_index('ix_approval_processes_created_at', 'approval_processes', ['created_at'], unique=False)
    op.create_index(op.f('ix_approval_processes_operator_id'), 'approval_processes', ['operator_id'], unique=False)
    op.create_index('ix_approval_processes_step', 'approval_processes', ['approval_id', 'step'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_approval_processes_step', table_name='approval_processes')
    op.drop_index(op.f('ix_approval_processes_operator_id'), table_name='approval_processes')
    op.drop_index('ix_approval_processes_created_at', table_name='approval_processes')
    op.drop_index(op.f('ix_approval_processes_approval_id'), table_name='approval_processes')
    op.drop_table('approval_processes')
    op.drop_index('ix_approval_notifications_recipient_read', table_name='approval_notifications')
    op.drop_index('ix_approval_notifications_recipient_id', table_name='approval_notifications')
    op.drop_index('ix_approval_notifications_is_read', table_name='approval_notifications')
    op.drop_index('ix_approval_notifications_created_at', table_name='approval_notifications')
    op.drop_index(op.f('ix_approval_notifications_approval_id'), table_name='approval_notifications')
    op.drop_table('approval_notifications')
    op.drop_index('ix_approvals_type', table_name='approvals')
    op.drop_index('ix_approvals_target_id', table_name='approvals')
    op.drop_index('ix_approvals_status_type', table_name='approvals')
    op.drop_index(op.f('ix_approvals_status'), table_name='approvals')
    op.drop_index('ix_approvals_created_at', table_name='approvals')
    op.drop_index(op.f('ix_approvals_applicant_id'), table_name='approvals')
    op.drop_table('approvals')
    # ### end Alembic commands ###
